### PR TITLE
Delete columns

### LINKED ISSUE #53: Only the first 14 rows are initially added to the cache, causing computeRowOffsets to malfunction when we are removing a column in a dataset with more than 14 columns.
**Actual behavior**
When testing the deleteColumn function the operation malfunctioned after the first 14 entries were removed. Random characters began being removed instead of the entry we wanted removed.

**Expected behavior**
All entries in the column we were removing would be removed, without effecting any other entries.

**To Reproduce**
1 .You can use this csv file.
2. Open Jupyterlab with the extension activated in the directory with the csv file saved.
3. Open the csv file with CSV Tabular Data Editor.
4. Do not scroll to the bottom of the file at any point. Simply navigate to a column header, right click it, and choose `delete column`
5. Now scroll down so the rest of the rows come into view. You should see something like this.

**Screenshots**
Screen Shot 2020-07-10 at 7 36 34 AM

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: firefox

### PR DESCRIPTION
**Pull request by lmcnichols**
# Description of the Pull Request

### Issue being fixed:
Fixes #53.

### Changes proposed:

- Added method `computeColumnOffsets`
- `computeColumnOffsets` is now called at the beginning whenever we call `addColumn` or `removeColumn`

### CODE REVIEW

File: src/model.ts [hunk 1]
```diff
@@ -316,6 +319,23 @@ export default class EditableDSVModel extends MutableDataModel {
       this._dsvModel.rawData.slice(this._colHeaderLength)
     );
   }
+
+  computeColumnOffsets() {
```
Comment (kgoo124) [inline src/model.ts:323]: Need to add a return type here though
