### PR TITLE
Fixes small bug with data types not updating on an undo/redo that changes the type.

### LINKED ISSUE #279: Data types don't update on undo/redo.
**Actual behavior**
A clear and concise description of what actually happened.
Data types do not update if an undo or a redo command changes the type.

**Expected behavior**
Datatypes should update if an undo or a redo changes the data type of the column.

**To Reproduce**
1. Set up a column to be almost numeric.
2. Turn on formatting.
3. Add numbers so the column becomes numeric.
4. Undo the last change you made.
(Do something like the inverse of this to see if for redo).

### PR DESCRIPTION
**Pull request by lmcnichols**
# Description of the Pull Request

Fixes small bug with data types not updating on an undo/redo that changes the type.

### Issue being fixed:
Fixes #279 

### Changes proposed:
- `onCommand` calls `updateModel` even if there is no `update` object. (causing it to be triggered on an undo & a redo)
- Bail statement in `updateModel` replaced with having all the model related stuff be wrapped in an if-statement. This achieves the same thing as the bail statement while letting us update the renderers AFTER we have updated the model.

### CODE REVIEW

File: src/widget.ts [hunk 1]
```diff
@@ -724,52 +724,49 @@ export class DSVEditor extends Widget {
...
+          selection: update.selection || null,
+          gridState: update.gridStateUpdate || null
+        }
+      );
+      this._litestore.endTransaction();
+    }
+
     if (this.dataModel.isDataFormatted) {
       this._updateRenderer();
     }
```
Comment (kgoo124) [inline src/widget.ts:769]: Is it possible to move these lines to the top and still have the bail statement? We don't want to nest things inside a conditional if we don't need to.

Comment (lmcnichols) [reply src/widget.ts:769]: I think it breaks if we do that b/c updateRenders activates a repaint before we have updated the model but let me give it a try.

Comment (lmcnichols) [reply src/widget.ts]: Yeah it seems to not serialize correctly if we do it that way. We get undefined values. My guess is that we end up having renders finding incorrect data types and somehow that get's marked as undefined. Not totally sure and this is probably worth investigating further. The current version seems to work.
